// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\clients\metricsClient.go

// Package mock_clients is a generated GoMock package.
package mockClients

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/yurchenkosv/metric-service/internal/model"
)

// MockMetricsClient is a mock of MetricsClient interface.
type MockMetricsClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsClientMockRecorder
}

// MockMetricsClientMockRecorder is the mock recorder for MockMetricsClient.
type MockMetricsClientMockRecorder struct {
	mock *MockMetricsClient
}

// NewMockMetricsClient creates a new mock instance.
func NewMockMetricsClient(ctrl *gomock.Controller) *MockMetricsClient {
	mock := &MockMetricsClient{ctrl: ctrl}
	mock.recorder = &MockMetricsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsClient) EXPECT() *MockMetricsClientMockRecorder {
	return m.recorder
}

// PushMetrics mockRepository base method.
func (m *MockMetricsClient) PushMetrics(metrics model.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushMetrics", metrics)
}

// PushMetrics indicates an expected call of PushMetrics.
func (mr *MockMetricsClientMockRecorder) PushMetrics(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMetrics", reflect.TypeOf((*MockMetricsClient)(nil).PushMetrics), metrics)
}
