// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: metric_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricServiceClient is the client API for MetricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricServiceClient interface {
	GetMetricByID(ctx context.Context, in *MetricRequestByID, opts ...grpc.CallOption) (*Metric, error)
	GetAllMetrics(ctx context.Context, in *MetricRequestAll, opts ...grpc.CallOption) (*Metrics, error)
	SaveMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*MetricResponse, error)
	SaveMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*MetricResponse, error)
}

type metricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricServiceClient(cc grpc.ClientConnInterface) MetricServiceClient {
	return &metricServiceClient{cc}
}

func (c *metricServiceClient) GetMetricByID(ctx context.Context, in *MetricRequestByID, opts ...grpc.CallOption) (*Metric, error) {
	out := new(Metric)
	err := c.cc.Invoke(ctx, "/api.MetricService/GetMetricByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) GetAllMetrics(ctx context.Context, in *MetricRequestAll, opts ...grpc.CallOption) (*Metrics, error) {
	out := new(Metrics)
	err := c.cc.Invoke(ctx, "/api.MetricService/GetAllMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) SaveMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*MetricResponse, error) {
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, "/api.MetricService/SaveMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) SaveMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*MetricResponse, error) {
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, "/api.MetricService/SaveMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServiceServer is the server API for MetricService service.
// All implementations should embed UnimplementedMetricServiceServer
// for forward compatibility
type MetricServiceServer interface {
	GetMetricByID(context.Context, *MetricRequestByID) (*Metric, error)
	GetAllMetrics(context.Context, *MetricRequestAll) (*Metrics, error)
	SaveMetric(context.Context, *Metric) (*MetricResponse, error)
	SaveMetrics(context.Context, *Metrics) (*MetricResponse, error)
}

// UnimplementedMetricServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMetricServiceServer struct {
}

func (UnimplementedMetricServiceServer) GetMetricByID(context.Context, *MetricRequestByID) (*Metric, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricByID not implemented")
}
func (UnimplementedMetricServiceServer) GetAllMetrics(context.Context, *MetricRequestAll) (*Metrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMetrics not implemented")
}
func (UnimplementedMetricServiceServer) SaveMetric(context.Context, *Metric) (*MetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMetric not implemented")
}
func (UnimplementedMetricServiceServer) SaveMetrics(context.Context, *Metrics) (*MetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMetrics not implemented")
}

// UnsafeMetricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricServiceServer will
// result in compilation errors.
type UnsafeMetricServiceServer interface {
	mustEmbedUnimplementedMetricServiceServer()
}

func RegisterMetricServiceServer(s grpc.ServiceRegistrar, srv MetricServiceServer) {
	s.RegisterService(&MetricService_ServiceDesc, srv)
}

func _MetricService_GetMetricByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).GetMetricByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetricService/GetMetricByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).GetMetricByID(ctx, req.(*MetricRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_GetAllMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricRequestAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).GetAllMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetricService/GetAllMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).GetAllMetrics(ctx, req.(*MetricRequestAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_SaveMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).SaveMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetricService/SaveMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).SaveMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_SaveMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).SaveMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetricService/SaveMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).SaveMetrics(ctx, req.(*Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricService_ServiceDesc is the grpc.ServiceDesc for MetricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MetricService",
	HandlerType: (*MetricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricByID",
			Handler:    _MetricService_GetMetricByID_Handler,
		},
		{
			MethodName: "GetAllMetrics",
			Handler:    _MetricService_GetAllMetrics_Handler,
		},
		{
			MethodName: "SaveMetric",
			Handler:    _MetricService_SaveMetric_Handler,
		},
		{
			MethodName: "SaveMetrics",
			Handler:    _MetricService_SaveMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metric_service.proto",
}
